name: Code Coverage and SCS

on:
  push:
    branches:
      - master

jobs:
  code-coverage:
    permissions:
        contents: read
        security-events: write
        actions: read
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: |
          coverage run --source=calculator -m unittest discover
          coverage xml -o coverage.xml
          coverage report

      - name: Convert to SARIF format
        run: coverage json -o custom_report.sarif

      - name: Upload custom SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: custom_report.sarif
