name: Code Coverage and SCS

on:
  push:
    branches:
      - master

jobs:
  code-coverage:
    permissions:
        contents: read
        security-events: write
        actions: read
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: |
          coverage run --source=calculator -m unittest discover
          coverage xml -o coverage.xml
          coverage report

      - name: Install CodeQL CLI
        run: |
          mkdir codeql-bin
          cd codeql-bin
          curl -L https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql.zip -o codeql.zip
          unzip codeql.zip
          export PATH="$PWD/codeql:$PATH"
      - name: Install CodeQL CLI
        run: |
            mkdir -p codeql-bin
            cd codeql-bin
            curl -L https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql.zip -o codeql.zip
            unzip codeql.zip
            export PATH="$PWD/codeql:$PATH"

      - name: Convert to SARIF format
        run: |
          codeql database create --language=python --source-root=. coverage
          codeql database create coverage --language=python --source-root=. --sarif=sarif_report.sarif
  
      - name: Upload SARIF report to GitHub for SCS
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif_report.sarif
  